export const currentFullNames: Record<string, object> = {
  "coord": { label: "Coordinates" },
  "lon": { label: "Longitude", type: "coordinate", unit: "" },
  "lat": { label: "Latitude", type: "coordinate", unit: "" },
  "weather": { label: "Weather" },
  "id": { label: "ID" },
  "main": { label: "Main" },
  "temp": { label: "Temperature", type: "temperature", unit: "°C" },
  "feels_like": { label: "Feels Like", type: "temperature", unit: "°C" },
  "temp_min": { label: "Minimum Temperature", type: "temperature", unit: "°C" },
  "temp_max": { label: "Maximum Temperature", type: "temperature", unit: "°C" },
  "temp_kf": { label: "Temperature Change", type: "temperature", unit: "°C" },
  "pressure": { label: "Pressure", type: "number", unit: "hPa" },
  "humidity": { label: "Humidity", type: "number", unit: "%" },
  "sea_level": { label: "Sea Level", type: "number", unit: "hPa" },
  "grnd_level": { label: "Ground Level", type: "number", unit: "hPa" },
  "visibility": { label: "Visibility", type: "number", unit: "m" },
  "wind": { label: "Wind" },
  "speed": { label: "Speed", type: "speed", unit: "m/s" },
  "deg": { label: "Degrees", type: "temperature", unit: "°C" },
  "gust": { label: "Gust", type: "number", unit: "m/s" },
  "clouds": { label: "Clouds" },
  "all": { label: "Clouds", type: "number", unit: "%" },
  "dt": { label: "Date/Time", type: "time", unit: "" },
  "dt_txt": { label: "Date/Time", type: "time", unit: "" },
  "sys": { label: "System" },
  "country": { label: "Country" },
  "sunrise": { label: "Sunrise", type: "time", unit: "" },
  "sunset": { label: "Sunset", type: "time", unit: "" },
  "timezone": { label: "Timezone", type: "timezone", unit: "" },
  "base": { label: "Base" },
  "name": { label: "Name" },
  "cod": { label: "Code" },
  "pod": { label: "Part of Day", type: "name", unit: "" },
  "pop": { label: "Precipitation", type: "number", unit: "" },
  "3h": { label: "3h", type: "number", unit: "" },

};